# Common Project Makefile
set(LIB_TARG common_project)

file(GLOB_RECURSE AURORA_COMMON_SOURCES FOLLOW_SYMLINKS 
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/log.c/src/*.c
)

add_library(${LIB_TARG} STATIC ${AURORA_COMMON_SOURCES})

# Required so this .a can be linked into a .so
set_target_properties(${LIB_TARG} PROPERTIES POSITION_INDEPENDENT_CODE ON)

target_include_directories(${LIB_TARG} PUBLIC 
    ${CMAKE_CURRENT_SOURCE_DIR}/include
    ${CMAKE_CURRENT_SOURCE_DIR}/log.c/src
)

target_compile_options(${LIB_TARG} PRIVATE ${GENERIC_COMPILE_OPTIONS})

target_link_libraries(${LIB_TARG} PRIVATE 
    ${COMMON_LIBRARIES}
    ${CMAKE_PROJECT_NAME}::ucx
)
